### ISSUE TITLE
train時發生錯誤，訊息如下

### ISSUE THREAD

**Issue by richardlotw** [dog-qiuqiu/Yolo-FastestV2#62]
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    _, _, AP, _ = utils.utils.evaluation(val_dataloader, cfg, model, device)
  File "D:\competition\Yolo-FastestV2-main\utils\utils.py", line 367, in evaluation
    for imgs, targets in pbar:
  File "C:\anaconda\envs\fire\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\dataloader.py", line 1229, in _process_data
    data.reraise()
  File "C:\anaconda\envs\fire\lib\site-packages\torch\_utils.py", line 434, in reraise
    raise exception
Exception: Caught Exception in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\anaconda\envs\fire\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\competition\Yolo-FastestV2-main\utils\datasets.py", line 127, in __getitem__
    raise Exception("%s is not exist" % label_path)
Exception: .txt is not exist

**Comment by richardlotw** [comment]
我是用絕對路徑，有這問題，我猜是datasets.py出問題 因為這裡寫在135-136行"if __name__ == "__main__":
    data = TensorDataset("/home/xuehao/Desktop/TMP/pytorch-yolo/widerface/train.txt")"這個位置怪怪的，但我帶我自己 train.txt還是有Exception: .txt is not exist的問題，困擾很久.......................

**Comment by richardlotw** [comment]
有誰可以幫幫忙??!

**Comment by lanmmn** [comment]
> > train.txt里的路径改成绝对路径，相对路径好像会有这个问题。
> 
> > 我是用絕對路徑，有這問題，我猜是datasets.py出問題 因為這裡寫在135-136行"if **name** == "**main**":
> > data = TensorDataset("/home/xuehao/Desktop/TMP/pytorch-yolo/widerface/train.txt")"這個位置怪怪的，但我帶我自己 train.txt還是有Exception: .txt is not exist的問題，困擾很久.......................
> 
> 我是用絕對路徑，有這問題，我猜是datasets.py出問題 因為這裡寫在135-136行"if name == "main": data = TensorDataset("/home/xuehao/Desktop/TMP/pytorch-yolo/widerface/train.txt")"這個位置怪怪的，但我帶我自己 train.txt還是有Exception: .txt is not exist的問題，困擾很久.......................

<img width="592" alt="image" src="https://github.com/dog-qiuqiu/Yolo-FastestV2/assets/81510157/bb4d8571-d0d3-4519-a63a-2041a923f690">
要注意datasets.py的label_path,他这边只以一个“.”为分隔符，如果你的标签文件带有多个“.”就会出问题。
